// Minimal load test for POST /api/complaints (create endpoint).
// Phases: 50 / 100 / 150 / 200 concurrent VUs. Each VU submits one complaint
// (the endpoint is @Public, so no auth is required) and records latency.
// Usage: node scripts/load-test.js
// Env: BASE_URL (default http://localhost:3001/api)

const BASE_URL = process.env.BASE_URL || "http://localhost:3001/api";
const PHASES = [50, 100, 150, 200];

function payload() {
  return {
    category: "SOFTWARE_HARDWARE",
    roomNo: String(Math.floor(Math.random() * 900) + 100),
    block: Math.random() < 0.5 ? "Q" : "S",
    rank: Math.floor(Math.random() * 30) + 1,
    contactMethod: Math.random() < 0.5 ? "PTCL" : "INTERCOMM",
    contactNumber: String(Math.floor(Math.random() * 1e7)),
    description: "Load test complaint generated by scripts/load-test.js",
  };
}

async function runPhase(vus) {
  const latencies = [];
  let errors = 0;
  const workers = Array.from({ length: vus }, async () => {
    const start = Date.now();
    try {
      const res = await fetch(`${BASE_URL}/complaints`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload()),
      });
      if (!res.ok) {
        errors++;
      }
    } catch {
      errors++;
    }
    latencies.push(Date.now() - start);
  });
  await Promise.all(workers);
  latencies.sort((a, b) => a - b);
  const p = (q) => latencies[Math.min(latencies.length - 1, Math.floor((q / 100) * latencies.length))];
  console.log(
    `VUs=${vus} count=${latencies.length} p50=${p(50)}ms p95=${p(95)}ms p99=${p(99)}ms max=${p(100)}ms errors=${errors}`
  );
}

async function main() {
  for (const vus of PHASES) {
    await runPhase(vus);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
